using System;
using System.Collections.Generic;
using System.Runtime.Intrinsics;
using IR2IL.Runtime;

namespace IR2IL.Intrinsics;

internal static class IntrinsicFunctions
{
    public static readonly Dictionary<string, IntrinsicFunction> LLVMIntrinsics = new()
    {
        // Standard intrinsics using Base Class Library methods.
        { "llvm.abs.i32", LLVMAbsIntIntrinsicFunction.Create(typeof(Math), typeof(int)) },
        { "llvm.abs.i64", LLVMAbsIntIntrinsicFunction.Create(typeof(Math), typeof(long)) },
        { "llvm.acos.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Acos)) },
        { "llvm.acos.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Acos)) },
        { "llvm.asin.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Asin)) },
        { "llvm.asin.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Asin)) },
        { "llvm.acos.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AcosV2F32)) },
        { "llvm.acos.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AcosV2F64)) },
        { "llvm.acos.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AcosV4F32)) },
        { "llvm.acos.v4f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AcosV4F64)) },
        { "llvm.asin.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AsinV2F32)) },
        { "llvm.asin.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AsinV2F64)) },
        { "llvm.asin.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AsinV4F32)) },
        { "llvm.asin.v4f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AsinV4F64)) },
        { "llvm.atan.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AtanV2F32)) },
        { "llvm.atan.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AtanV2F64)) },
        { "llvm.atan.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AtanV4F32)) },
        { "llvm.atan.v4f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.AtanV4F64)) },
        { "llvm.atan.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Atan)) },
        { "llvm.atan.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Atan)) },
        { "llvm.atan2.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Atan2)) },
        { "llvm.atan2.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Atan2)) },
        { "llvm.atan2.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Atan2V2F32)) },
        { "llvm.atan2.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Atan2V2F64)) },
        { "llvm.atan2.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Atan2V4F32)) },
        { "llvm.ceil.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Ceiling), typeof(double)) },
        { "llvm.copysign.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.CopySign)) },
        { "llvm.copysign.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.CopySign)) },
        { "llvm.cos.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Cos)) },
        { "llvm.cos.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Cos)) },
        { "llvm.cos.v2f32", StandardIntrinsicFunction.Create(typeof(Vector64), nameof(Vector64.Cos), typeof(Vector64<float>)) },
        { "llvm.cos.v2f64", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Cos), typeof(Vector128<double>)) },
        { "llvm.cos.v4f32", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Cos), typeof(Vector128<float>)) },
        { "llvm.cos.v4f64", StandardIntrinsicFunction.Create(typeof(Vector256), nameof(Vector256.Cos), typeof(Vector256<double>)) },
        { "llvm.cosh.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Cosh)) },
        { "llvm.cosh.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Cosh)) },
        { "llvm.cosh.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.CoshV2F32)) },
        { "llvm.cosh.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.CoshV2F64)) },
        { "llvm.ctpop.i8", StandardIntrinsicFunction.Create(typeof(sbyte), nameof(sbyte.PopCount), typeof(sbyte)) },
        { "llvm.ctpop.i16", StandardIntrinsicFunction.Create(typeof(short), nameof(short.PopCount), typeof(short)) },
        { "llvm.exp.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Exp)) },
        { "llvm.exp.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Exp)) },
        { "llvm.exp.v2f32", StandardIntrinsicFunction.Create(typeof(Vector64), nameof(Vector64.Exp), typeof(Vector64<float>)) },
        { "llvm.exp.v2f64", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Exp), typeof(Vector128<double>)) },
        { "llvm.exp.v4f32", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Exp), typeof(Vector128<float>)) },
        { "llvm.exp.v4f64", StandardIntrinsicFunction.Create(typeof(Vector256), nameof(Vector256.Exp), typeof(Vector256<double>)) },
        { "llvm.fabs.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Abs)) },
        { "llvm.fabs.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Abs), typeof(double)) },
        { "llvm.fmuladd.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.FusedMultiplyAdd)) },
        { "llvm.fmuladd.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.FusedMultiplyAdd)) },
        { "llvm.fmuladd.v2f32", StandardIntrinsicFunction.Create(typeof(Vector64), nameof(Vector64.FusedMultiplyAdd), typeof(Vector64<float>), typeof(Vector64<float>), typeof(Vector64<float>)) },
        { "llvm.fmuladd.v2f64", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.FusedMultiplyAdd), typeof(Vector128<double>), typeof(Vector128<double>), typeof(Vector128<double>)) },
        { "llvm.fmuladd.v4f32", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.FusedMultiplyAdd), typeof(Vector128<float>), typeof(Vector128<float>), typeof(Vector128<float>)) },
        { "llvm.fmuladd.v4f64", StandardIntrinsicFunction.Create(typeof(Vector256), nameof(Vector256.FusedMultiplyAdd), typeof(Vector256<double>), typeof(Vector256<double>), typeof(Vector256<double>)) },
        { "llvm.is.fpclass.f32", new LLVMIsFPClassIntrinsicFunction(isDouble: false) },
        { "llvm.is.fpclass.f64", new LLVMIsFPClassIntrinsicFunction(isDouble: true) },
        { "llvm.log.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Log), typeof(float)) },
        { "llvm.log.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Log), typeof(double)) },
        { "llvm.log.v2f32", StandardIntrinsicFunction.Create(typeof(Vector64), nameof(Vector64.Log), typeof(Vector64<float>)) },
        { "llvm.log.v2f64", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Log), typeof(Vector128<double>)) },
        { "llvm.log.v4f32", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Log), typeof(Vector128<float>)) },
        { "llvm.log.v4f64", StandardIntrinsicFunction.Create(typeof(Vector256), nameof(Vector256.Log), typeof(Vector256<double>)) },
        { "llvm.log10.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Log10)) },
        { "llvm.log10.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Log10)) },
        { "llvm.log10.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Log10V2F32)) },
        { "llvm.log10.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Log10V2F64)) },
        { "llvm.log10.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Log10V4F32)) },
        { "llvm.log10.v4f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Log10V4F64)) },
        { "llvm.pow.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Pow)) },
        { "llvm.pow.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Pow)) },
        { "llvm.pow.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.PowV2F32)) },
        { "llvm.pow.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.PowV2F64)) },
        { "llvm.pow.v4f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.PowV4F32)) },
        { "llvm.pow.v4f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.PowV4F64)) },
        { "llvm.sin.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Sin)) },
        { "llvm.sin.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Sin)) },
        { "llvm.sin.v2f32", StandardIntrinsicFunction.Create(typeof(Vector64), nameof(Vector64.Sin), typeof(Vector64<float>)) },
        { "llvm.sin.v2f64", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Sin), typeof(Vector128<double>)) },
        { "llvm.sin.v4f32", StandardIntrinsicFunction.Create(typeof(Vector128), nameof(Vector128.Sin), typeof(Vector128<float>)) },
        { "llvm.sin.v4f64", StandardIntrinsicFunction.Create(typeof(Vector256), nameof(Vector256.Sin), typeof(Vector256<double>)) },
        { "llvm.sinh.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Sinh)) },
        { "llvm.sinh.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Sinh)) },
        { "llvm.sinh.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.SinhV2F32)) },
        { "llvm.sinh.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.SinhV2F64)) },
        { "llvm.scmp.i32.i32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.Scmp)) },
        { "llvm.smin.i32", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Min), typeof(int), typeof(int)) },
        { "llvm.smax.i32", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Max), typeof(int), typeof(int)) },
        { "llvm.smax.i64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Max), typeof(long), typeof(long)) },
        { "llvm.smax.v4i32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Max), typeof(int)) },
        { "llvm.sqrt.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Sqrt)) },
        { "llvm.sqrt.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Sqrt)) },
        { "llvm.sqrt.v2f32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector64), nameof(Vector64.Sqrt), typeof(float)) },
        { "llvm.sqrt.v2f64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sqrt), typeof(double)) },
        { "llvm.sqrt.v4f32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sqrt), typeof(float)) },
        { "llvm.sqrt.v4f64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector256), nameof(Vector256.Sqrt), typeof(double)) },
        { "llvm.tan.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Tan)) },
        { "llvm.tan.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Tan)) },
        { "llvm.tan.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.TanV2F32)) },
        { "llvm.tan.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.TanV2F64)) },
        { "llvm.tanh.f32", StandardIntrinsicFunction.Create(typeof(MathF), nameof(MathF.Tanh)) },
        { "llvm.tanh.f64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Tanh)) },
        { "llvm.tanh.v2f32", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.TanhV2F32)) },
        { "llvm.tanh.v2f64", StandardIntrinsicFunction.Create(typeof(VectorUtility), nameof(VectorUtility.TanhV2F64)) },
        { "llvm.umin.i32", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Min), typeof(uint), typeof(uint)) },
        { "llvm.umax.i64", StandardIntrinsicFunction.Create(typeof(Math), nameof(Math.Max), typeof(ulong), typeof(ulong)) },
        { "llvm.vector.reduce.add.v4i64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector256), nameof(Vector256.Sum), typeof(long)) },
        { "llvm.vector.reduce.add.v8i32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector256), nameof(Vector256.Sum), typeof(int)) },
        { "llvm.vector.reduce.add.v8i64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector512), nameof(Vector512.Sum), typeof(long)) },
        { "llvm.vector.reduce.add.v2i64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sum), typeof(long)) },
        { "llvm.vector.reduce.add.v4i16", StandardIntrinsicFunction.CreateGeneric(typeof(Vector64), nameof(Vector64.Sum), typeof(short)) },
        { "llvm.vector.reduce.add.v4i32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sum), typeof(int)) },
        { "llvm.vector.reduce.add.v8i16", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sum), typeof(short)) },
        { "llvm.vector.reduce.add.v16i8", StandardIntrinsicFunction.CreateGeneric(typeof(Vector128), nameof(Vector128.Sum), typeof(sbyte)) },
        { "llvm.vector.reduce.add.v16i16", StandardIntrinsicFunction.CreateGeneric(typeof(Vector256), nameof(Vector256.Sum), typeof(short)) },
        { "llvm.vector.reduce.add.v16i32", StandardIntrinsicFunction.CreateGeneric(typeof(Vector512), nameof(Vector512.Sum), typeof(int)) },
        { "llvm.vector.reduce.add.v16i64", StandardIntrinsicFunction.CreateGeneric(typeof(Vector1024), nameof(Vector1024.Sum), typeof(long)) },

        // Standard intrinsics using custom methods.
        { "llvm.vector.reduce.fadd.v2f64", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceFAddV2F64)) },
        { "llvm.vector.reduce.fadd.v4f32", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceFAddV4F32)) },
        { "llvm.vector.reduce.mul.v4i32", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceMulV4I32)) },
        { "llvm.vector.reduce.mul.v16i8", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceMulV16I8)) },
        { "llvm.vector.reduce.mul.v16i16", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceMulV16I16)) },
        { "llvm.vector.reduce.smax.v4i32", StandardIntrinsicFunction.Create(typeof(LLVMIntrinsics), nameof(Runtime.LLVMIntrinsics.VectorReduceSMaxV4I32)) },

        // Irregular intrinsics.
        { "llvm.dbg.declare", new LLVMDbgDeclareIntrinsicFunction() },
        { "llvm.memcpy.p0.p0.i64", new LLVMMemCpyI64IntrinsicFunction() },
        { "llvm.memmove.p0.p0.i64", new LLVMMemCpyI64IntrinsicFunction() },
        { "llvm.memset.p0.i64", new LLVMMemSetI64IntrinsicFunction() },
        { "llvm.stacksave", new LLVMStackSaveIntrinsicFunction() },
        { "llvm.stacksave.p0", new LLVMStackSaveIntrinsicFunction() },
        { "llvm.threadlocal.address.p0", new LLVMThreadLocalAddressIntrinsicFunction() },
        { "llvm.usub.sat.i32", new LLVMUSubSatI32IntrinsicFunction() },
        { "llvm.va_start.p0", new LLVMVaStartIntrinsicFunction() },

        { "llvm.objectsize.i64.p0", new LLVMObjectSizeIntrinsicFunction() },

        // No-op intrinsics.
        { "llvm.assume", NoOpIntrinsicFunction.Instance },
        { "llvm.dbg.label", NoOpIntrinsicFunction.Instance },
        { "llvm.dbg.value", NoOpIntrinsicFunction.Instance },
        { "llvm.experimental.noalias.scope.decl", NoOpIntrinsicFunction.Instance },
        { "llvm.lifetime.start.p0", NoOpIntrinsicFunction.Instance },
        { "llvm.lifetime.end.p0", NoOpIntrinsicFunction.Instance },
        { "llvm.stackrestore", NoOpIntrinsicFunction.Instance },
        { "llvm.stackrestore.p0", NoOpIntrinsicFunction.Instance }
    };
}
