name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Cache downloaded LLVM zip
      uses: actions/cache@v5
      with:
        key: build-cache-${{ runner.os }}-${{ hashFiles('src/IR2IL.Tests/IR2IL.Tests.csproj') }}
        path: build/cache

    - name: Install .NET
      uses: actions/setup-dotnet@v5

    - name: Build & Test Debug
      run: dotnet test src --configuration Debug

    - name: Build & Test Release
      run: dotnet test src --configuration Release